name: Get Fix Commits

on:
  workflow_dispatch:
      
jobs:

  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydriller
        pip install requests

    - name: Get Fix Commits
      run: |
        python get_fix_commits.py

    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add json/with_fix_commits/*.json
        git commit -m "Get Fix Commits"
        git push