name: RUN PD2
on:
  workflow_dispatch:
      
jobs:

  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydriller
        pip install requests

    - name: Get Fix Commits
      run: |
        python run_pd2.py

    # - name: Remover Raw Data File
    #   run: |
    #     git rm ${{ matrix.file }}
    #     git add json/raw_data/*.json
        
    - name: Commit and push
      run: |
        git config --global user.email "thiagogquinto.dev@gmail.com"
        git config --global user.name "Thiago Quinto"
        git pull 
        git add json/final_processed/*.json
        git commit -m "Add PyDriller"
        git push